---
title: "Network Linked Data Index Update and Client Applications"
author: "David Blodgett"
slug: "nldi_update"
date: "2020-01-07"
keyword1: "NHDPlus"
output: USGSmarkdowntemplates::hugo
description:  "An update on the Network Linked Data Index Web Application Programming Interface and Client Applications"
author_email: dblodgett@usgs.gov
author_github: dblodgett-usgs
author_twitter: D_Blodgett
author_staff: david-l-blodgett
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
knit_hooks$set(plot=function(x, options) {
  sprintf("{{<figure src='/%s%s-%d.%s' title='%s' alt='%s' >}}",
          options$fig.path, options$label,
          options$fig.cur, options$fig.ext,
          options$fig.cap, options$alt.text)
})
opts_chunk$set(
  echo=TRUE,
  fig.path="static/nldi_update/",
  fig.cap = "TODO",
  alt.text = "TODO",
  fig.width = 7,
  fig.height = 5,
  class = "",
  message = FALSE,
  warnings = FALSE
)
```

In August 2020, the Hydro Network Linked Data Index (NLDI) was updated with some new functionality and some changes to the existing Web Application Programming Interface (API). This post summarizes these changes and demonstrates Python and R clients available to work with the functionality. 

If you are new to the NLDI, visit the [nldi-intro](https://waterdata.usgs.gov/blog/nldi-intro/) blog to get up to speed. This post assumes a basic understanding of the API.

## Summary

The new functionality added to the NLDI is the ability to retrieve local or accumulated catchment characteristics for any `featureSource` available from the system. A selection of characteristics from [this data release](https://www.sciencebase.gov/catalog/item/5669a79ee4b08895842a1d470) are included. This is detailed further down in this post.

API changes are backward compatible but fairly significant.
- If using a web-browser, `?f=json` needs to be appended to requests to see JSON content.
- The `navigate` endpoint is deprecated in favor of a `navigation` end point with slightly different behavior.
-- previously, a `navigate/{navigationMode}` request would return flowlines. The `navigation/{navigationMode}` endpoint now returns available `dataSources`, treating flowlines as a data source.
-- The upstream with tributaries `navigationMode` now requires the `distance` query parameter. Unconstrained upstream with tributaries queries (the default from the `navigate` endpoint) were causing system performance problems. Client applications must now explicitly request very large upstream with tributaries queries to avoid performance issues due to naive client requests.
- All features in a `featureSource` can now be accessed at the `featureSource` endpoint. This will allow clients to easily create map-based selection interfaces.
- A `featureSource` can now be queried with a lat/lon point encoded in `WKT` format.

## API Updates Detail

lorum ipsum

## New Catchment Characteristics

lorum ipsum

## Python Client Application

lorum ipsum

## R client Application

lorum ipsum
